
NORMAL_SEND_ATTEMPTS = 10
NORMAL_RECEIVE_ATTEMPTS = 100

CONNECTION_ERROR_ATTEMPTS = 100
NON_DET_ERROR_ATTEMPTS = 2
SCAN_MIN_ATTEMPTS = 10
SCAN_MAX_ATTEMPTS =50
CONNECT_MIN_ATTEMPTS = 5
CONNECT_MAX_ATTEMPTS = 20
NORMAL_MIN_ATTEMPTS = 10
NORMAL_MAX_ATTEMPTS = 30
TERMINATE_MIN_ATTEMPTS = 2
TERMINATE_MAX_ATTEMPTS = 6
MIN_ATTEMPTS = 10
MAX_ATTEMPTS = 200
PHYSICAL_RESET = False
LOG_PCAP = True
MAX_FUZZING_CEX_REPETITIONS = 5
NON_DET_CACHE_SIZE = 5
EMPTY = "empty"
ERROR = "error"
EXIT = "exit"
TIMEOUT = 10


